Repository FC-Chilli-Bubble/back-officener, pull requests merged in 2023-10, with the labels that each got.

#145 DTO 리팩토링 작업 완료
  src/main/java/fastcampus/team7/Livable_officener/controller/ElevatorController.java
  src/main/java/fastcampus/team7/Livable_officener/controller/NotificationController.java
  src/main/java/fastcampus/team7/Livable_officener/dto/elevator/ElevatorDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/notification/NotificationDTO.java
  src/main/java/fastcampus/team7/Livable_officener/service/ElevatorService.java
  src/main/java/fastcampus/team7/Livable_officener/service/NotificationService.java
  src/main/resources/application.yml
Labels: refactor

#146 로그아웃 기능 추가 및 로그인, 회원가입 리펙터링 및 테스트 코드 추가 완료
  src/main/java/fastcampus/team7/Livable_officener/controller/SignUpController.java
  src/main/java/fastcampus/team7/Livable_officener/dto/BuildingDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/BuildingWithCompaniesDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/CompanyDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/LoginDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/LoginRequestDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/LoginResponseDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/PhoneAuthConfirmDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/PhoneAuthDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/PhoneAuthRequestDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/PhoneAuthResponseDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/RedisRepositoryConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/FilterExceptionCode.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/AlreadyLogoutException.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/InvalidPasswordException.java
  src/main/java/fastcampus/team7/Livable_officener/global/sercurity/JwtExceptionFilter.java
  src/main/java/fastcampus/team7/Livable_officener/global/sercurity/JwtProvider.java
  src/main/java/fastcampus/team7/Livable_officener/global/util/APIExceptionHandler.java
  src/main/java/fastcampus/team7/Livable_officener/global/util/RedisUtil.java
  src/main/java/fastcampus/team7/Livable_officener/service/SignUpService.java
  src/test/java/fastcampus/team7/Livable_officener/config/EmbeddedRedisConfig.java
  src/test/java/fastcampus/team7/Livable_officener/controller/LoginControllerTest.java
  src/test/java/fastcampus/team7/Livable_officener/controller/SignUpControllerTest.java
  src/test/java/fastcampus/team7/Livable_officener/repository/BuildingRepositoryTest.java
  src/test/java/fastcampus/team7/Livable_officener/repository/PhoneAuthDTORedisRepositoryTest.java
  src/test/java/fastcampus/team7/Livable_officener/service/LoginServiceTest.java
  src/test/java/fastcampus/team7/Livable_officener/service/SignUpServiceTest.java
Labels: feature, fix, refactor

#152 refactor #150: JWT 제공자 및 필터
  src/main/java/fastcampus/team7/Livable_officener/global/sercurity/JwtAuthenticationFilter.java
  src/main/java/fastcampus/team7/Livable_officener/global/sercurity/JwtProvider.java
Labels: refactor

#154 메소드 이름 변경에 따른 수정
  src/main/java/fastcampus/team7/Livable_officener/global/sercurity/JwtProvider.java
  src/main/java/fastcampus/team7/Livable_officener/service/SignUpService.java
  src/test/java/fastcampus/team7/Livable_officener/service/LoginServiceTest.java
Labels: refactor

#155 기본 웹소켓 보안 설정 #148
  src/main/java/fastcampus/team7/Livable_officener/domain/User.java
  src/main/java/fastcampus/team7/Livable_officener/global/sercurity/JwtProvider.java
  src/main/java/fastcampus/team7/Livable_officener/global/websocket/CustomHandshakeHandler.java
  src/main/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManager.java
  src/test/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManagerAddSessionToRoomTest.java
  src/test/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManagerNonexistentTest.java
  src/test/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManagerSendTest.java
Labels: feature, fix

#159 채팅방 참여하기(정보 요청) 응답 포맷 수정
  src/main/java/fastcampus/team7/Livable_officener/controller/ChatController.java
  src/main/java/fastcampus/team7/Livable_officener/dto/chat/GetParticipantDTO.java
Labels: fix

#166 Refactor/#157 package refactor
  src/main/java/fastcampus/team7/Livable_officener/controller/SignUpController.java
  src/main/java/fastcampus/team7/Livable_officener/dto/login/LoginDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/signup/BuildingWithCompaniesDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/signup/PhoneAuthDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/signup/SignUpRequestDTO.java
  src/main/java/fastcampus/team7/Livable_officener/service/SignUpService.java
  src/test/java/fastcampus/team7/Livable_officener/controller/LoginControllerTest.java
  src/test/java/fastcampus/team7/Livable_officener/controller/SignUpControllerTest.java
  src/test/java/fastcampus/team7/Livable_officener/service/LoginServiceTest.java
  src/test/java/fastcampus/team7/Livable_officener/service/SignUpServiceTest.java
Labels: refactor

#169 엘리베이터 리팩토링 완료
  src/main/java/fastcampus/team7/Livable_officener/controller/ElevatorController.java
  src/main/java/fastcampus/team7/Livable_officener/service/ElevatorService.java
Labels: refactor

#171 fix #170: 채팅방 정보 요청 시 회원의 id 오류
  src/main/java/fastcampus/team7/Livable_officener/dto/chat/GetParticipantDTO.java
Labels: fix

#173 fix #172: 패키지 경로
  build.gradle
  gradlew
  src/main/java/fastcampus/team7/Livable_officener/repository/PhoneAuthDTORedisRepository.java
Labels: fix

#179 '참여 마감' 시스템 메시지 송신 시 수신자 이름 기준으로 content 생성
  src/main/java/fastcampus/team7/Livable_officener/domain/User.java
  src/main/java/fastcampus/team7/Livable_officener/dto/chat/SendPayloadDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/ChatType.java
  src/main/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManager.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
  src/test/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManagerAddSessionToRoomTest.java
  src/test/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManagerNonexistentTest.java
  src/test/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManagerSendDynamicMessageToAllTest.java
  src/test/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManagerSendToAllTest.java
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceCompleteDeliveryTest.java
Labels: fix

#182 fix #181: JSR-310 적용
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
Labels: fix

#180 '채팅방 참여하기 (정보 요청)' 수정 #165
  build.gradle
  src/main/java/fastcampus/team7/Livable_officener/dto/chat/GetMessageDTO.java
  src/main/java/fastcampus/team7/Livable_officener/repository/ChatRepository.java
  src/main/java/fastcampus/team7/Livable_officener/repository/JpaChatRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceGetRoomInfoTest.java
Labels: fix

#188 fix #183: 직렬화 필드 이름 설정
  build.gradle
  src/main/java/fastcampus/team7/Livable_officener/dto/chat/GetParticipantDTO.java
Labels: fix

#189 엘리베이터 목록 수정 완료
  src/main/java/fastcampus/team7/Livable_officener/repository/UserElevatorRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/ElevatorService.java
Labels: refactor

#190 POST /api/chat/{roomId}/enter 참여자 첫 입장 #109
  build.gradle
  src/main/java/fastcampus/team7/Livable_officener/controller/ChatController.java
  src/main/java/fastcampus/team7/Livable_officener/dto/chat/GetParticipantDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/chat/SendPayloadDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/ChatType.java
  src/main/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManager.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
  src/test/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManagerSendEnterMessageToAllTest.java
Labels: feature, test

#192 불필요한 import 정리 및 라인 포매팅, 불필요한 파일 정리 #191
  src/main/java/fastcampus/team7/Livable_officener/controller/.gitkeep
  src/main/java/fastcampus/team7/Livable_officener/domain/TestRoom.java
  src/main/java/fastcampus/team7/Livable_officener/global/error/.gitkeep
  src/main/java/fastcampus/team7/Livable_officener/global/exception/.gitkeep
  src/main/java/fastcampus/team7/Livable_officener/global/response/.gitkeep
  src/main/java/fastcampus/team7/Livable_officener/global/sercurity/.gitkeep
  src/main/java/fastcampus/team7/Livable_officener/repository/.gitkeep
  src/main/java/fastcampus/team7/Livable_officener/service/.gitkeep
  src/test/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManagerNonexistentTest.java
  src/test/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManagerSendDynamicMessageToAllTest.java
  src/test/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManagerSendEnterMessageToAllTest.java
Labels: chore

#199 함께배달 상세, 채팅리스트 DTO 수정
  src/main/java/fastcampus/team7/Livable_officener/dto/delivery/ChatRoomListResponseDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/delivery/RoomDetailDTO.java
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryRepositoryImpl.java
  src/main/java/fastcampus/team7/Livable_officener/service/DeliveryService.java
Labels: refactor

#193 FCM 알림 #125
  build.gradle
  src/main/java/fastcampus/team7/Livable_officener/controller/FCMController.java
  src/main/java/fastcampus/team7/Livable_officener/domain/Notification.java
  src/main/java/fastcampus/team7/Livable_officener/dto/fcm/FCMNotificationDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/fcm/FCMSubscribeDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/RedisRepositoryConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/ChatType.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/NotificationContent.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/NotificationType.java
  src/main/java/fastcampus/team7/Livable_officener/global/fcm/FCMTokenRepository.java
  src/main/java/fastcampus/team7/Livable_officener/global/fcm/FirebaseConfig.java
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryParticipantRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
  src/main/java/fastcampus/team7/Livable_officener/service/DeliveryService.java
  src/main/java/fastcampus/team7/Livable_officener/service/FCMService.java
  src/main/java/fastcampus/team7/Livable_officener/service/NotificationService.java
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceSendTest.java
Labels: feature, fix

#201 참여마감 스케쥴링 #196
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/DeliveryScheduleService.java
Labels: feature

#203 이체 마감 임박(5분 전) 시 모든 게스트에게 알림 송신 #197
  build.gradle
  src/main/java/fastcampus/team7/Livable_officener/dto/fcm/FCMNotificationDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/SchedulingConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/ChatType.java
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
  src/main/java/fastcampus/team7/Livable_officener/service/DeliveryScheduleService.java
Labels: feature

#210 POST /api/notify/fcm-token 규약 변경 #204
  build.gradle
  src/main/java/fastcampus/team7/Livable_officener/controller/FCMController.java
  src/main/java/fastcampus/team7/Livable_officener/dto/fcm/FCMSubscribeDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/fcm/FCMUpdateRequestDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/FCMNotificationStatus.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/FCMNotificationStatusUpdateType.java
  src/main/java/fastcampus/team7/Livable_officener/global/fcm/FCMNotificationStatusRepository.java
  src/main/java/fastcampus/team7/Livable_officener/global/fcm/FCMTokenRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/FCMService.java
Labels: fix

#213 호스트 퇴장 시 채팅방 상태 변경
  src/main/java/fastcampus/team7/Livable_officener/domain/Room.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
Labels: fix

#207 HTTPS 설정 확인 컨트롤러 및 cors 설정 추가 완료
  src/main/java/fastcampus/team7/Livable_officener/controller/HealthController.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/SecurityConfig.java
Labels: feature

#214 refactor chat room list id 로 정렬 추가
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryRepositoryImpl.java
Labels: refactor

#220 마감 시간 지난 함께배달 참여마감 상태로 변경할 때 쿼리 변경 #215
  src/main/java/fastcampus/team7/Livable_officener/global/config/SchedulingConfig.java
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryRepository.java
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryRepositoryCustom.java
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryRepositoryImpl.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
Labels: fix

#222 Redis email to Value(fcmToken, status) 템플릿 정의 #221
  src/main/java/fastcampus/team7/Livable_officener/controller/FCMController.java
  src/main/java/fastcampus/team7/Livable_officener/dto/fcm/FCMStatusDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/fcm/FCMUpdateRequestDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/RedisRepositoryConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/fcm/FCMNotificationStatusRepository.java
  src/main/java/fastcampus/team7/Livable_officener/global/fcm/FCMStatusRepository.java
  src/main/java/fastcampus/team7/Livable_officener/global/fcm/FCMTokenRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/FCMService.java
Labels: fix

#223 마감 임박 함께배달 조회 쿼리 수정 #216
  build.gradle
  src/main/java/fastcampus/team7/Livable_officener/global/config/SchedulingConfig.java
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryRepository.java
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryRepositoryCustom.java
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryRepositoryImpl.java
  src/main/java/fastcampus/team7/Livable_officener/service/FCMService.java
Labels: fix

#225 API 명세서에 맞게 FCMUpdateRequestDTO 필드 이름 변경 #224
  src/main/java/fastcampus/team7/Livable_officener/dto/fcm/FCMStatusDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/fcm/FCMUpdateRequestDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/fcm/FCMStatusRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/FCMService.java
Labels: fix

#227 Fix/#226 chore
  build.gradle
  src/main/java/fastcampus/team7/Livable_officener/controller/DeliveryController.java
  src/main/java/fastcampus/team7/Livable_officener/dto/fcm/FCMStatusDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/JacksonConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/WebMvcConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/interceptor/LogInterceptor.java
  src/main/java/fastcampus/team7/Livable_officener/global/util/APIExceptionHandler.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
Labels: fix, chore

#229 Fix/#228 connect validation
  build.gradle
  src/main/java/fastcampus/team7/Livable_officener/global/exception/AccessTerminatedRoomException.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/AlreadyLogoutException.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/NotFoundUserException.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/RemitNotCompletedException.java
  src/main/java/fastcampus/team7/Livable_officener/global/util/APIExceptionHandler.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
Labels: fix, chore

#231 fix #230: 마감 및 마감알림 스케쥴 쿼리 수정
  build.gradle
  src/main/java/fastcampus/team7/Livable_officener/global/config/SchedulingConfig.java
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryRepositoryCustom.java
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryRepositoryImpl.java
Labels: fix

#235 fix #232: 호스트에게 보내는 푸시알림 메시지 내용 수정
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
Labels: fix

#236 Fix/#234 websocket handshake security
  src/main/java/fastcampus/team7/Livable_officener/global/config/SecurityConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/WebMvcConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketUpgradeMatcher.java
Labels: fix

#238 첫 입장 시 함께배달 방 존재하지 않는 문제
  src/main/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManager.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
  src/main/java/fastcampus/team7/Livable_officener/service/DeliveryService.java
Labels: fix

#239 fix #237: 기본 시간대 설정
  src/main/java/fastcampus/team7/Livable_officener/LivableOfficenerApplication.java
Labels: fix

#241 불필요한 코드 제거, 예외 리팩토링 #240
  build.gradle
  src/main/java/fastcampus/team7/Livable_officener/global/config/SecurityConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/AlreadyExistsWebSocketSession.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/EmptyFCMToken.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/EmptyFCMUpdateRequestType.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/NonUniqueHost.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/NotFoundFCMToken.java
  src/main/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManager.java
  src/main/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketUpgradeMatcher.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
  src/main/java/fastcampus/team7/Livable_officener/service/FCMService.java
Labels: fix

#243 fix #242: 이체마감임박(=5분 전) 스케쥴 쿼리 수정
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryRepositoryImpl.java
Labels: fix

#247 일반 및 웹소켓 시큐리티 origin 설정 수정
  build.gradle
  src/main/java/fastcampus/team7/Livable_officener/global/config/SecurityConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketConfig.java
Labels: fix

#245 test #244: 종료 상태인 경우만 예외 (마감 상태에서도 호출 가능)
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceGetRoomInfoTest.java
Labels: test
