Repository FC-Chilli-Bubble/back-officener, pull requests merged in 2023-09, with the labels that each got.

#9 웹소켓 설정
  src/main/java/fastcampus/team7/Livable_officener/global/config/.gitkeep
  src/main/java/fastcampus/team7/Livable_officener/global/config/WebSocketConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/handler/CustomTextWebSocketHandler.java
Labels: feature

#19 일반 메시지 송신 기능 기초 작업 및 채팅방 입퇴장 수정
  src/main/java/fastcampus/team7/Livable_officener/domain/Chat.java
  src/main/java/fastcampus/team7/Livable_officener/dto/SendChatDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/WebSocketConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/handler/CustomTextWebSocketHandler.java
  src/main/java/fastcampus/team7/Livable_officener/global/interceptor/CustomHandshakeInterceptor.java
  src/main/java/fastcampus/team7/Livable_officener/repository/ChatRepository.java
  src/main/java/fastcampus/team7/Livable_officener/repository/ChatRoomRepository.java
  src/main/java/fastcampus/team7/Livable_officener/repository/JpaChatRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
Labels: feature, chore

#25 refactor #24: RoomStatus 이름 변경
  src/main/java/fastcampus/team7/Livable_officener/global/constant/RoomStatus.java
Labels: refactor

#29 참여마감 #22
  src/main/java/fastcampus/team7/Livable_officener/controller/ChatController.java
  src/main/java/fastcampus/team7/Livable_officener/domain/Room.java
  src/main/java/fastcampus/team7/Livable_officener/dto/SendChatDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/WebSocketConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/ChatType.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/SystemMessage.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/NotActiveRoomException.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/NotFoundRoomException.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/UserIsNotHostException.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/UserIsNotParticipantException.java
  src/main/java/fastcampus/team7/Livable_officener/global/handler/CustomTextWebSocketHandler.java
  src/main/java/fastcampus/team7/Livable_officener/global/interceptor/CustomHandshakeInterceptor.java
  src/main/java/fastcampus/team7/Livable_officener/global/util/APIExceptionHandler.java
  src/main/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManager.java
  src/main/java/fastcampus/team7/Livable_officener/repository/XChatRoomParticipantRepository.java
  src/main/java/fastcampus/team7/Livable_officener/repository/XChatRoomRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
  src/test/java/fastcampus/team7/Livable_officener/domain/RoomTest.java
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceTest.java
Labels: feature, refactor, test

#34 feat #16: 함께 배달 상세 페이지 구현 및 querydsl 종속성 추가
  build.gradle
  src/main/java/fastcampus/team7/Livable_officener/controller/DeliveryController.java
  src/main/java/fastcampus/team7/Livable_officener/dto/RoomDetailDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/QuerydslConfig.java
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryRepository.java
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryRepositoryCustom.java
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryRepositoryImpl.java
  src/main/java/fastcampus/team7/Livable_officener/service/DeliveryService.java
Labels: feature

#39 fix #38: WebSocketConfig 순환참조 해결
  src/main/java/fastcampus/team7/Livable_officener/global/config/WebSocketConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/handler/CustomTextWebSocketHandler.java
  src/main/java/fastcampus/team7/Livable_officener/global/interceptor/CustomHandshakeInterceptor.java
  src/main/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManager.java
Labels: fix

#33 Feat/#30 transfer complete
  src/main/java/fastcampus/team7/Livable_officener/controller/ChatController.java
  src/main/java/fastcampus/team7/Livable_officener/domain/BaseEntity.java
  src/main/java/fastcampus/team7/Livable_officener/domain/RoomParticipant.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/ChatType.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/SystemMessage.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/AlreadyTransferredException.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/UserIsNotGuestException.java
  src/main/java/fastcampus/team7/Livable_officener/repository/XChatRoomParticipantRepository.java
  src/main/java/fastcampus/team7/Livable_officener/repository/XChatRoomRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
  src/test/java/fastcampus/team7/Livable_officener/domain/RoomParticipantTest.java
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceTransferCompleteTest.java
Labels: feature, fix

#42 회원가입 로직 구현 완료
  build.gradle
  src/main/java/fastcampus/team7/Livable_officener/controller/SignUpController.java
  src/main/java/fastcampus/team7/Livable_officener/domain/Building.java
  src/main/java/fastcampus/team7/Livable_officener/domain/Company.java
  src/main/java/fastcampus/team7/Livable_officener/domain/User.java
  src/main/java/fastcampus/team7/Livable_officener/dto/BuildingWithCompaniesDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/CompanyDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/PhoneAuthConfirmDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/PhoneAuthDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/PhoneAuthRequestDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/SignUpRequestDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/EmbeddedRedisConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/RedisRepositoryConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/SecurityConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/sercurity/CustomUserDetails.java
  src/main/java/fastcampus/team7/Livable_officener/global/sercurity/CustomUserDetailsService.java
  src/main/java/fastcampus/team7/Livable_officener/global/sercurity/JwtAuthenticationFilter.java
  src/main/java/fastcampus/team7/Livable_officener/global/sercurity/JwtProvider.java
  src/main/java/fastcampus/team7/Livable_officener/repository/BuildingRepository.java
  src/main/java/fastcampus/team7/Livable_officener/repository/CompanyRepository.java
  src/main/java/fastcampus/team7/Livable_officener/repository/UserRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/SignUpService.java
  src/main/resources/application.yml
  src/test/java/fastcampus/team7/Livable_officener/config/QueryDslConfig.java
  src/test/java/fastcampus/team7/Livable_officener/controller/SignUpControllerTest.java
  src/test/java/fastcampus/team7/Livable_officener/repository/BuildingRepositoryTest.java
  src/test/java/fastcampus/team7/Livable_officener/service/SignUpServiceTest.java
Labels: feature, test

#43 리팩토링: 참여마감하기
  src/main/java/fastcampus/team7/Livable_officener/global/constant/SystemMessage.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceCloseParticipationTest.java
Labels: refactor

#48 엘리베이터 리스트 api 구현 완료
  .gitignore
  build.gradle
  src/main/java/fastcampus/team7/Livable_officener/controller/ElevatorController.java
  src/main/java/fastcampus/team7/Livable_officener/dto/ElevatorDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/SecurityConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/WebClientConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/ElevatorStatus.java
  src/main/java/fastcampus/team7/Livable_officener/global/util/GenerateSig.java
  src/main/java/fastcampus/team7/Livable_officener/repository/ElevatorRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/ElevatorService.java
  src/main/resources/application.yml
Labels: feature

#51 엘리베이터 리스트 수정 완료
  src/main/java/fastcampus/team7/Livable_officener/controller/DeliveryController.java
  src/main/java/fastcampus/team7/Livable_officener/controller/ElevatorController.java
  src/main/java/fastcampus/team7/Livable_officener/domain/UserElevator.java
  src/main/java/fastcampus/team7/Livable_officener/dto/ElevatorDTO.java
  src/main/java/fastcampus/team7/Livable_officener/service/DeliveryService.java
  src/main/java/fastcampus/team7/Livable_officener/service/ElevatorService.java
Labels: refactor

#62 엘리베이터 설정 구현 완료.
  src/main/java/fastcampus/team7/Livable_officener/controller/ElevatorController.java
  src/main/java/fastcampus/team7/Livable_officener/domain/UserElevator.java
  src/main/java/fastcampus/team7/Livable_officener/dto/ElevatorDTO.java
  src/main/java/fastcampus/team7/Livable_officener/repository/UserElevatorRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/ElevatorService.java
Labels: feature, refactor

#63 Feat#61 receive complete
  src/main/java/fastcampus/team7/Livable_officener/controller/ChatController.java
  src/main/java/fastcampus/team7/Livable_officener/domain/RoomParticipant.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/SystemMessage.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/AlreadyReceivedException.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceReceiveCompleteTest.java
Labels: feature, test

#65 배달 완료 #57
  src/main/java/fastcampus/team7/Livable_officener/controller/ChatController.java
  src/main/java/fastcampus/team7/Livable_officener/domain/Room.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/SystemMessage.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/AlreadyDeliveredException.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
  src/test/java/fastcampus/team7/Livable_officener/domain/RoomCloseParticipationTest.java
  src/test/java/fastcampus/team7/Livable_officener/domain/RoomCompleteDeliveryTest.java
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceCompleteDeliveryTest.java
Labels: feature, test

#66 회원가입 테스트 코드 및 로직 구현 완료
  src/main/java/fastcampus/team7/Livable_officener/controller/SignUpController.java
  src/main/java/fastcampus/team7/Livable_officener/dto/PhoneAuthDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/SignUpRequestDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/SecurityConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/DuplicatedPhoneNumberException.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/NotFoundBuildingException.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/NotVerifiedPhoneNumberException.java
  src/main/java/fastcampus/team7/Livable_officener/global/util/APIExceptionHandler.java
  src/main/java/fastcampus/team7/Livable_officener/service/SignUpService.java
  src/test/java/fastcampus/team7/Livable_officener/controller/SignUpControllerTest.java
  src/test/java/fastcampus/team7/Livable_officener/repository/BuildingRepositoryTest.java
  src/test/java/fastcampus/team7/Livable_officener/repository/PhoneAuthDTORedisRepositoryTest.java
  src/test/java/fastcampus/team7/Livable_officener/service/SignUpServiceTest.java
Labels: feature, refactor, test

#67 test(fix) #57: 배달완료시 Room#배달완료 호출 후 예외 미발생 수정
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceCompleteDeliveryTest.java
Labels: fix, test

#72 Feature #56 나의 채팅탭 구현
  src/main/java/fastcampus/team7/Livable_officener/controller/DeliveryController.java
  src/main/java/fastcampus/team7/Livable_officener/dto/ChatRoomListResponseDTO.java
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryRepositoryCustom.java
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryRepositoryImpl.java
  src/main/java/fastcampus/team7/Livable_officener/service/DeliveryService.java
Labels: feature

#74 fix #73: ChatService 의존성 변경
  src/main/java/fastcampus/team7/Livable_officener/global/interceptor/CustomHandshakeInterceptor.java
  src/main/java/fastcampus/team7/Livable_officener/repository/TestRoomRepository.java
  src/main/java/fastcampus/team7/Livable_officener/repository/XChatRoomParticipantRepository.java
  src/main/java/fastcampus/team7/Livable_officener/repository/XChatRoomRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceCloseParticipationTest.java
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceCompleteDeliveryTest.java
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceReceiveCompleteTest.java
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceRemitCompleteTest.java
Labels: fix

#76 나가기 요청 구현 완료
  src/main/java/fastcampus/team7/Livable_officener/controller/ChatController.java
  src/main/java/fastcampus/team7/Livable_officener/controller/DeliveryController.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/SecurityConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/SystemMessage.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
Labels: feature

#80 Feat#64 호스트 나가기 기능 구현
  src/main/java/fastcampus/team7/Livable_officener/controller/ChatController.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/ReceiveNotCompletedException.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/RemitNotCompletedException.java
  src/main/java/fastcampus/team7/Livable_officener/repository/DeliveryParticipantRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceExitChatRoomTest.java
Labels: feature, fix, test

#83 로그인 구현 및 JWT 관련 로직 리펙터링
  src/main/java/fastcampus/team7/Livable_officener/controller/SignUpController.java
  src/main/java/fastcampus/team7/Livable_officener/dto/LoginRequestDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/LoginResponseDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/SecurityConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/JwtExceptionCode.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/DuplicatedUserEmailException.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/NotFoundUserException.java
  src/main/java/fastcampus/team7/Livable_officener/global/sercurity/JwtAuthenticationFilter.java
  src/main/java/fastcampus/team7/Livable_officener/global/sercurity/JwtExceptionFilter.java
  src/main/java/fastcampus/team7/Livable_officener/global/sercurity/JwtProvider.java
  src/main/java/fastcampus/team7/Livable_officener/global/util/APIExceptionHandler.java
  src/main/java/fastcampus/team7/Livable_officener/repository/UserRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/SignUpService.java
Labels: feature, fix, refactor

#89 SignUpControllerTest 에러 처리 해결
  src/test/java/fastcampus/team7/Livable_officener/controller/SignUpControllerTest.java
Labels: fix

#82 ChatType, SystemMessage enum 통합 및 웹소켓 송신 구조 변경 #75
  build.gradle
  src/main/java/fastcampus/team7/Livable_officener/controller/ChatController.java
  src/main/java/fastcampus/team7/Livable_officener/controller/NotificationController.java
  src/main/java/fastcampus/team7/Livable_officener/domain/BaseEntity.java
  src/main/java/fastcampus/team7/Livable_officener/domain/Chat.java
  src/main/java/fastcampus/team7/Livable_officener/dto/NotificationDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/chat/SendChatDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/chat/SendPayloadDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/ChatType.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/SystemMessage.java
  src/main/java/fastcampus/team7/Livable_officener/global/handler/CustomTextWebSocketHandler.java
  src/main/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManager.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceCompleteDeliveryTest.java
Labels: fix

#90 refactor/#77 notification
  src/main/java/fastcampus/team7/Livable_officener/controller/NotificationController.java
Labels: refactor

#91 feat #12: 공통 응답 설정 및 예러 해결
  src/main/java/fastcampus/team7/Livable_officener/global/util/APIDataResponse.java
  src/main/java/fastcampus/team7/Livable_officener/service/ElevatorService.java
  src/main/java/fastcampus/team7/Livable_officener/service/NotificationService.java
Labels: feature

#94 공통 응답 수정 #12
  src/main/java/fastcampus/team7/Livable_officener/controller/DeliveryController.java
  src/main/java/fastcampus/team7/Livable_officener/controller/SignUpController.java
  src/main/java/fastcampus/team7/Livable_officener/global/util/APIDataResponse.java
  src/main/java/fastcampus/team7/Livable_officener/service/ElevatorService.java
  src/main/java/fastcampus/team7/Livable_officener/service/NotificationService.java
Labels: feature, fix

#95 fix #12: 공통 에러 응답 클래스 수정
  src/main/java/fastcampus/team7/Livable_officener/global/util/APIErrorResponse.java
Labels: fix

#96 채팅방 참여하기 #71
  src/main/java/fastcampus/team7/Livable_officener/controller/ChatController.java
  src/main/java/fastcampus/team7/Livable_officener/domain/RoomParticipant.java
  src/main/java/fastcampus/team7/Livable_officener/domain/User.java
  src/main/java/fastcampus/team7/Livable_officener/dto/chat/ChatroomInfoDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/chat/GetMessageDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/chat/GetParticipantDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/interceptor/CustomHandshakeInterceptor.java
  src/main/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManager.java
  src/main/java/fastcampus/team7/Livable_officener/repository/ChatRepository.java
  src/main/java/fastcampus/team7/Livable_officener/repository/JpaChatRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceGetRoomInfoTest.java
Labels: feature

#101 fix #100: 유저 엔티티 생성 시 회사 지정
  src/main/java/fastcampus/team7/Livable_officener/dto/SignUpRequestDTO.java
  src/main/java/fastcampus/team7/Livable_officener/repository/CompanyRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/SignUpService.java
Labels: fix

#102 Feat#98 report
  src/main/java/fastcampus/team7/Livable_officener/controller/ChatController.java
  src/main/java/fastcampus/team7/Livable_officener/domain/Report.java
  src/main/java/fastcampus/team7/Livable_officener/dto/chat/ReportDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/constant/ReportType.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/AlreadyReportSameUserException.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/NotFoundReportedUserException.java
  src/main/java/fastcampus/team7/Livable_officener/repository/ReportRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
Labels: feature, fix

#108 Feature/#107 read notify
  src/main/java/fastcampus/team7/Livable_officener/controller/NotificationController.java
  src/main/java/fastcampus/team7/Livable_officener/global/config/SecurityConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/util/APIDataResponse.java
  src/main/java/fastcampus/team7/Livable_officener/service/NotificationService.java
Labels: feature

#116 시큐리티 CORS 해결
  src/main/java/fastcampus/team7/Livable_officener/global/config/SecurityConfig.java
Labels: feature, fix

#119 알림 목록 수정 완료
  src/main/java/fastcampus/team7/Livable_officener/dto/NotificationDTO.java
  src/main/java/fastcampus/team7/Livable_officener/service/NotificationService.java
Labels: refactor

#122 메시지 송신 시 읽지 않은 메시지 수 업데이트 #97
  src/main/java/fastcampus/team7/Livable_officener/domain/BaseEntity.java
  src/main/java/fastcampus/team7/Livable_officener/domain/RoomParticipant.java
  src/main/java/fastcampus/team7/Livable_officener/domain/User.java
  src/main/java/fastcampus/team7/Livable_officener/dto/chat/SendPayloadDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/util/LocalDateTimeDeserializer.java
  src/main/java/fastcampus/team7/Livable_officener/global/websocket/CustomHandshakeInterceptor.java
  src/main/java/fastcampus/team7/Livable_officener/global/websocket/CustomTextWebSocketHandler.java
  src/main/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketConfig.java
  src/main/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManager.java
  src/main/java/fastcampus/team7/Livable_officener/service/ChatService.java
  src/test/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManagerAddSessionToRoomTest.java
  src/test/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManagerNonexistentTest.java
  src/test/java/fastcampus/team7/Livable_officener/global/websocket/WebSocketSessionManagerSendTest.java
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceCompleteDeliveryTest.java
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceExitChatRoomTest.java
  src/test/java/fastcampus/team7/Livable_officener/service/ChatServiceSendTest.java
Labels: feature, fix, test

#126 회원가입시 Validaiton 기능 추가 및 회원가입 테스트 코드 작성 완료
  src/main/java/fastcampus/team7/Livable_officener/controller/SignUpController.java
  src/main/java/fastcampus/team7/Livable_officener/domain/Building.java
  src/main/java/fastcampus/team7/Livable_officener/dto/BuildingWithCompaniesDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/LoginRequestDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/PhoneAuthResponseDTO.java
  src/main/java/fastcampus/team7/Livable_officener/dto/SignUpRequestDTO.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/DuplicatedUserEmailException.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/NotFoundCompanyException.java
  src/main/java/fastcampus/team7/Livable_officener/global/exception/NotVerifiedPhoneAuthCodeException.java
  src/main/java/fastcampus/team7/Livable_officener/global/util/APIExceptionHandler.java
  src/main/java/fastcampus/team7/Livable_officener/repository/UserRepository.java
  src/main/java/fastcampus/team7/Livable_officener/service/SignUpService.java
  src/test/java/fastcampus/team7/Livable_officener/controller/SignUpControllerTest.java
  src/test/java/fastcampus/team7/Livable_officener/service/SignUpServiceTest.java
Labels: feature, refactor, test

#132 빌드 배포하는 과정에서 발생하는 로그아웃 로직 삭제 완료
  src/main/java/fastcampus/team7/Livable_officener/service/SignUpService.java
Labels: fix
